//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HeatBox.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_HEATBOX_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_SWITCH               129
#define IDD_DIALOG_CURVE                130
#define IDI_ICON_RED                    132
#define IDD_DIALOG_PARA                 133
#define IDD_DIALOG_DEBUG                135
#define IDD_DIALOG_TAKEOUT              137
#define IDD_DIALOG_TAKEOUT_PAGE         140
#define IDD_DIALOG_RECORD_VIEW          141
#define IDD_DIALOG_TEMP_PARA            142
#define IDD_DIALOG_CREAT_MODIFY_PARA    143
#define IDD_DIALOG_PRODUCT_BAR          145
#define IDD_DIALOG_PRN_PREVIEW          147
#define IDD_DIALOG_ADJUST_WIZARD_1      148
#define IDD_DIALOG_CHANLIANG_TONGJI     149
#define IDD_DIALOG_INPUT_PID_TEMP       151
#define IDD_DIALOG_GLASS_TEMP           152
#define IDB_BITMAP_TAKE_BOARD           154
#define IDD_INPUT_DIALOG                155
#define IDB_BITMAP_TAKE_BOARD1          155
#define IDB_BITMAP_TESTING              155
#define IDD_DIALOG_INPUT_GLASS_TEMP     156
#define IDD_DIALOG_INFOMATION           157
#define IDD_DIALOG_TEMP_ADJUST          160
#define IDC_TAB1                        1000
#define IDC_TAB2                        1001
#define IDC_TAB3                        1002
#define IDC_TAB4                        1003
#define IDC_TAB5                        1004
#define IDC_TAB6                        1005
#define IDC_TAB7                        1006
#define IDC_TAB8                        1007
#define IDC_TAB9                        1008
#define IDC_TAB10                       1009
#define IDC_MSCHART1                    1012
#define IDC_EDIT_MAIN_LEVEL_LOW         1013
#define IDC_EDIT_HIGH_LEVEL_LOW         1014
#define IDC_EDIT_MAIN_LEVEL_HIGH        1015
#define IDC_EDIT_MAIN_LEVEL_SPAN        1015
#define IDC_EDIT_HIGH_LEVEL_HIGH        1016
#define IDC_EDIT_LOW_LEVEL_HIGH         1018
#define IDC_EDIT_LOW_LEVEL_SPAN         1018
#define IDC_EDIT_OVER_HIGH_LEVEL        1019
#define IDC_EDIT_CLOSE_MAIN_LEVEL_SPAN_MINUS 1019
#define IDC_EDIT_OVER_LOW_LEVEL         1020
#define IDC_BUTTON_SAVE                 1023
#define IDC_EDIT_CLOSE_LEVEL4           1023
#define IDC_COMBO1                      1025
#define IDC_EDIT_CLOSE_LEVEL_SPAN_PLUS4 1025
#define IDC_COMBO2                      1026
#define IDC_EDIT_CLOSE_LEVEL5           1026
#define IDC_COMBO_PARA_TYPE             1026
#define IDC_COMBO_SWITCH_NR             1026
#define IDC_COMBO3                      1027
#define IDC_EDIT_CLOSE_LEVEL_SPAN_PLUS5 1027
#define IDC_COMBO_SWITCH_NR2            1027
#define IDC_COMBO4                      1028
#define IDC_COMBO5                      1029
#define IDC_COMBO_TEST_MODE             1029
#define IDC_COMBO6                      1030
#define IDC_COMBO_CUR_MAX_HEAT_BOX      1030
#define IDC_COMBO7                      1031
#define IDC_COMBO_HEAT_BOX_TYPE         1031
#define IDC_COMBO8                      1032
#define IDC_COMBO_DISPLAY_TEMP_TYPE     1032
#define IDC_EDIT1                       1033
#define IDC_COMBO_485_PROTOCOL          1033
#define IDC_EDIT2                       1034
#define IDC_COMBO_END_TEST_DOOR_STATUS  1034
#define IDC_EDIT3                       1035
#define IDC_EDIT4                       1036
#define IDC_CHECK_AUTO_PROCESS          1036
#define IDC_EDIT5                       1037
#define IDC_BUTTON_TAKEOUT              1037
#define IDC_EDIT6                       1038
#define IDC_CHECK_NEXT_PAGE             1038
#define IDC_CHECK_MAIN_LEVEL            1039
#define IDC_EDIT_TAKEOUT_TIME           1039
#define IDC_CHECK_HIGH_LEVEL            1040
#define IDC_EDIT_1                      1040
#define IDC_EDIT_CLOSE_MAIN_LEVEL_SPAN_PLUS 1040
#define IDC_EDIT_MAIN_LEVEL2            1040
#define IDC_CHECK_LOW_LEVEL             1041
#define IDC_EDIT7                       1041
#define IDC_EDIT_2                      1041
#define IDC_CHECK_OVER_HIGH_LEVEL       1042
#define IDC_EDIT8                       1042
#define IDC_EDIT_3                      1042
#define IDC_CHECK_OVER_LOW_LEVEL        1043
#define IDC_EDIT9                       1043
#define IDC_EDIT_4                      1043
#define IDC_EDIT_HEAT_DEGREE            1043
#define IDC_CHECK_CLOSE_HIGH_LEVEL      1044
#define IDC_EDIT10                      1044
#define IDC_RADIO_CLOSE                 1044
#define IDC_EDIT_COOL_DEGREE            1044
#define IDC_CHECK_CLOSE_LOW_LEVEL       1045
#define IDC_EDIT11                      1045
#define IDC_RADIO_OPEN                  1045
#define IDC_EDIT12                      1046
#define IDC_CHECK_OPEN_FLASH            1046
#define IDC_EDIT_5                      1046
#define IDC_EDIT13                      1047
#define IDC_STATIC_TEST_MSG             1047
#define IDC_CHECK_CLOSE_FLASH           1047
#define IDC_EDIT14                      1048
#define IDC_CHECK_OPEN_DOOR_RESET       1048
#define IDC_BUTTON1                     1049
#define IDC_EDIT15                      1049
#define IDC_BUTTON2                     1050
#define IDC_EDIT16                      1050
#define IDC_BUTTON3                     1051
#define IDC_COMBO_FLASH_GAP             1051
#define IDC_CHECK_HIGH_HIGH_LEVEL       1051
#define IDC_BUTTON4                     1052
#define IDC_CHECK_HIGH_LEVEL_CLOSE_HIGH_LEVEL 1052
#define IDC_BUTTON5                     1053
#define IDC_EDIT_LOW_LEVEL_LOW          1053
#define IDC_CHECK_HIGH_LEVEL_CLOSE_LOW_LEVEL 1053
#define IDC_BUTTON6                     1054
#define IDC_EDIT_OPEN_FLASH_LEVEL       1054
#define IDC_EDIT_CLOSE_LEVEL2           1054
#define IDC_BUTTON7                     1055
#define IDC_EDIT_CLOSE_FLASH_LEVEL      1055
#define IDC_BUTTON8                     1056
#define IDC_EDIT_OPEN_DOOR_RESET        1056
#define IDC_EDIT_CLOSE_LEVEL3           1056
#define IDC_BUTTON9                     1057
#define IDC_EDIT_CLOSE_LEVEL_SPAN_PLUS3 1057
#define IDC_BUTTON10                    1058
#define IDC_EDIT_CLOSE_LEVEL_SPAN_PLUS8 1058
#define IDC_EDIT_CLOSE_LOW_LEVEL_DEVIATION_PLUS 1058
#define IDC_BUTTON11                    1059
#define IDC_EDIT_HIGH_HIGH_LEVEL        1059
#define IDC_BUTTON12                    1060
#define IDC_CHECK_LOW_LEVEL_CLOSE_HIGH_LEVEL 1060
#define IDC_BUTTON13                    1061
#define IDC_CHECK_LOW_LEVEL_CLOSE_LOW_LEVEL 1061
#define IDC_BUTTON1_SAVE                1062
#define IDC_CHECK_NO_PTC_LEVEL          1062
#define IDC_BUTTON14                    1062
#define IDC_BUTTON_READ                 1063
#define IDC_EDIT_NO_PTC_LEVEL           1063
#define IDC_COMBO_PARA_NAME             1066
#define IDC_STATIC_VERSION              1067
#define IDC_COMBO_OPEN_DOOR_RESET_LEVEL 1067
#define IDC_STATIC_COMPILE_TIME         1068
#define IDC_BUTTON17                    1069
#define IDC_STATIC_MSG                  1069
#define IDC_RADIO_ONLY_ONE              1070
#define IDC_RADIO_MULTI_SELECT          1071
#define IDC_BUTTON_BOARD_ADJUST         1071
#define IDC_STATIC_DATA_AREA            1072
#define IDC_RADIO_ALL_SELECT            1072
#define IDC_CHECK_HIGH_VOLT             1073
#define IDC_BUTTON20                    1074
#define IDC_RADIO_HIGHT_EN              1074
#define IDC_RADIO_HIGHT_DIS             1075
#define IDC_BUTTON_OPEN_DOOR            1075
#define IDC_CHECK_RELAY                 1076
#define IDC_CHECK_COOL_RELAY            1077
#define IDC_BUTTON18                    1078
#define IDC_SCROLLBAR_SWITCH_ID         1078
#define IDC_BUTTON19                    1079
#define IDC_CHECK_COOL_RELAY2           1080
#define IDC_SCROLLBAR1                  1081
#define IDC_STATIC_TIME_MSG             1082
#define IDC_CHECK_NO_ACTION             1088
#define IDC_BUTTON_SYNCHRONIZATION_BEGIN 1088
#define IDC_EDIT_NO_ACTION_LEVEL        1089
#define IDC_BUTTON_RECORD_VIEW          1089
#define IDC_BUTTON_RESET                1090
#define IDC_BUTTON_RECORD_VIEW2         1090
#define IDC_EDIT_TOTAL                  1090
#define IDC_BUTTON_READ_SYNCHRONIZATION 1091
#define IDC_MONTHCALENDAR1              1091
#define IDC_CHECK_NO_LEVEL              1091
#define IDC_CHECK_NO_ACTION2            1092
#define IDC_EDIT_NO_LEVEL               1092
#define IDC_LIST_RECORD                 1093
#define IDC_BUTTON_TEMP_VIEW            1093
#define IDC_LIST_RECORD_TIME            1094
#define IDC_BUTTON_SAVE_EXCEL           1094
#define IDC_STATIC_PARA                 1095
#define IDC_BUTTON_PREVIEW              1095
#define IDC_BUTTON_PRN                  1096
#define IDC_BUTTON_TODAY_CHANLIANG      1096
#define IDC_STATIC_BOX_MSG              1097
#define IDC_BUTTON_TEMP_BAR             1097
#define IDC_BUTTON_COPYRIGHT            1098
#define IDC_BUTTON_PRN_PREVIEW          1098
#define IDC_LIST_TEST_RESULT            1099
#define IDC_RADIO_OPEN_TEMP             1099
#define IDC_BUTTON_PRN2                 1099
#define IDC_BUTTON_TAKEDLG              1099
#define IDC_BUTTON_TAKEOUT_DLG          1100
#define IDC_RADIO_CLOSE_TEMP            1100
#define IDC_BUTTON_TEST                 1102
#define IDC_STATIC_MAIN_LEVEL           1103
#define IDC_SAVE                        1103
#define IDC_STATIC_HIGH_LEVEL           1104
#define IDC_DELETE                      1104
#define IDC_STATIC_LOW_LEVEL            1105
#define IDC_LIST_PARA_NAME              1105
#define IDC_EDIT_CLOSE_MAIN_LEVEL       1106
#define IDC_EDIT_PARA_NAME              1106
#define IDC_BUTTON_HIGH_VOLT            1107
#define IDC_BUTTON_CREATE_MODIFY_PARA   1107
#define IDC_STATIC_PARA_NAME            1108
#define IDC_BUTTON_SET_ADJUST_ALL       1108
#define IDC_BUTTON_READ_ADJUST_ALL      1109
#define IDC_RADIO_LED_STATUS            1110
#define IDC_RADIO_LED_ALL_ON            1111
#define IDC_COMBO_HEAT_SPEED            1112
#define IDC_RADIO_LED_ALL_OFF           1112
#define IDC_COMBO_HEAT_SPEED2           1113
#define IDC_COMBO_COOL_DEGREE           1113
#define IDC_EDIT_CLOSE_LEVEL_SPAN_MINUS3 1115
#define IDC_BUTTON_LOGO                 1116
#define IDC_EDIT_HIGH_LEVEL_CLOSE_HIGH_LEVEL 1116
#define IDC_COMBO_COOL_SPEED            1116
#define IDC_BUTTON_ADJUST_WIZARD        1117
#define IDC_EDIT_HIGH_LEVEL_CLOSE_LOW_LEVEL 1117
#define IDC_EDIT_CLOSE_LOW_LEVEL_DEVIATION_MINUS 1117
#define IDC_EDIT_MSG                    1118
#define IDC_EDIT_LOW_LEVEL_CLOSE_HIGH_LEVEL 1118
#define IDC_EDIT_METER_TEMP_1           1119
#define IDC_EDIT_LOW_LEVEL_CLOSE_LOW_LEVEL 1119
#define IDC_EDIT_METER_TEMP_2           1120
#define IDC_EDIT_METER_TEMP_3           1121
#define IDC_EDIT_METER_TEMP_4           1122
#define IDC_EDIT_GLASS_TEMP_1           1123
#define IDC_EDIT_GLASS_TEMP_2           1124
#define IDC_EDIT_GLASS_TEMP_3           1125
#define IDC_EDIT_GLASS_TEMP_4           1126
#define IDC_EDIT_METER_ADJUS_LOW_1      1127
#define IDC_EDIT_METER_ADJUS_LOW_2      1128
#define IDC_EDIT_PC_TIME                1128
#define IDC_EDIT_METER_ADJUS_LOW_3      1129
#define IDC_EDIT_SOFT_TIME              1129
#define IDC_EDIT_METER_ADJUS_LOW_4      1130
#define IDC_EDIT_SOFT_SN                1130
#define IDC_EDIT_METER_ADJUS_HIGH_1     1131
#define IDC_EDIT_PC_SN                  1131
#define IDC_EDIT_METER_ADJUS_HIGH_2     1132
#define IDC_BUTTON_SAVE_SN              1132
#define IDC_EDIT_METER_ADJUS_HIGH_3     1133
#define IDC_EDIT_SOFT_TIME2             1133
#define IDC_EDIT_METER_ADJUS_HIGH_4     1134
#define IDC_EDIT_PC_TIME2               1134
#define IDC_BUTTON_CRACK                1135
#define IDC_BUTTON_TONGJI               1136
#define IDC_BUTTON_SAVEAS               1137
#define IDC_MONTHCALENDAR2              1138
#define IDC_BUTTON_SAVEAS2              1138
#define IDC_BUTTON_VIEW                 1139
#define IDC_BUTTON_PRINT                1140
#define IDC_BUTTON_SAVE_CSV             1141
#define IDC_EDIT_YEAR                   1142
#define IDC_EDIT_MONTH                  1143
#define IDC_EDIT_CLOSE_HIGH_LEVEL_MINUS 1143
#define IDC_EDIT_DAY                    1144
#define IDC_EDIT_SET_ADJUST_ALL         1145
#define IDC_EDIT_READ_ADJUST_ALL        1146
#define IDC_STATIC_FLASH                1146
#define IDC_BUTTON_NEXT                 1147
#define IDC_CHECK_RESET                 1149
#define IDC_BUTTON_CAL_TEMP             1150
#define IDC_CAL_MSG                     1151
#define IDC_EDIT_PID_TEMP               1152
#define IDC_DATETIMEPICKER_START_TIME   1154
#define IDC_DATETIMEPICKER_END_TIME     1155
#define IDC_BUTTON_1                    1155
#define IDC_BUTTON_2                    1156
#define IDC_BUTTON_3                    1157
#define IDC_BUTTON_4                    1158
#define IDC_BUTTON_5                    1159
#define IDC_BUTTON_6                    1160
#define IDC_BUTTON_7                    1161
#define IDC_BUTTON_8                    1162
#define IDC_BUTTON_9                    1163
#define IDC_BUTTON_0                    1164
#define IDC_BUTTON_DOT                  1165
#define IDC_BUTTON_CLEAR                1166
#define IDC_BUTTON_PLUS_MINUS           1167
#define IDC_RADIO1                      1168
#define IDC_RADIO2                      1169
#define IDC_STATIC_HEAT                 1170
#define IDC_STATIC_COOL                 1171
#define IDC_EDIT_PID_MINUTES            1172
#define IDC_STATIC_MINUS_SPAN           1173
#define IDC_STATIC_PLUS_SPAN            1174
#define IDC_EDIT_GLASS_2                1175
#define IDC_EDIT_GLASS_1                1176
#define IDC_EDIT_SEND_CMD_COUNT         1176
#define IDC_EDIT_GLASS_3                1177
#define IDC_EDIT_RECEIVE_CMD_COUNT      1177
#define IDC_EDIT_CONTINUE_TEST_COUNT    1177
#define IDC_EDIT_GLASS_4                1178
#define IDC_MSCHART2                    1178
#define IDC_STATIC_PARA_4               1179
#define IDC_STATIC_COPYWRITE_DAYS       1180
#define IDC_COMBO_CURVE_TYPE            1181
#define IDC_DATETIMEPICKER_START_DAY    1182
#define IDC_EDIT_MODIFY_HISTORY         1183
#define IDC_STATIC_SOFT_TIME            1184
#define IDC_STATIC_SOFT_SN              1185
#define IDC_STATIC_PC_TIME              1186
#define IDC_EDIT_USER                   1187
#define IDC_EDIT_DIALOG_TITLE           1188
#define IDC_STATIC_INFO                 1189
#define IDC_EDIT_COMM_TIMER             1189
#define IDC_EDIT_MEMO                   1190
#define IDC_CTL4RA1                     1191
#define IDC_COMBO_SORT_TYPE             1192
#define IDC_CHECK_STOP_TEST_TYPE        1193
#define IDC_COMBO_PRINT_TYPE            1193
#define IDC_CHECK_STOP_TEST_TYPE2       1194
#define IDC_MONTHCALENDAR3              1195
#define IDC_COMBO_HIGH_HIGH_LEVEL_DELTA 1196
#define IDC_BUTTON_LAST_VERSION         1198
#define IDC_EDIT_COMM_REC               1199
#define IDC_EDIT_COMM_SEND              1200
#define IDC_BUTTON_TEMP_ADJUST          1200
#define IDC_EDIT_COMM_SEND2             1201
#define IDC_STATIC_STATUS               1201
#define IDC_STATIC_OPEN_TEMP_LOW        1202
#define IDC_STATIC_OPEN_TEMP_HIGH       1203
#define IDC_STATIC_CLOSE_TEMP_LOW       1204
#define IDC_STATIC_CLOSE_TEMP_HIGH      1205
#define IDC_EDIT_OPEN_TEMP_LOW          1206
#define IDC_EDIT_OPEN_TEMP_HIGH         1207
#define IDC_EDIT_CLOSE_TEMP_LOW         1208
#define IDC_EDIT_CLOSE_TEMP_HIGH        1209
#define IDC_BUTTON_RECORD               1210
#define IDC_EDIT_PARA1                  2001
#define IDC_EDIT_PARA2                  2002
#define IDC_EDIT_PARA3                  2003
#define IDC_EDIT_PARA4                  2004
#define IDC_EDIT_PARA5                  2005
#define IDC_EDIT_PARA6                  2006
#define IDC_EDIT_PARA7                  2007
#define IDC_EDIT_PARA8                  2008
#define IDC_EDIT_PARA9                  2009
#define IDC_EDIT_PARA10                 2010
#define IDC_EDIT_PARA11                 2011
#define IDC_EDIT_PARA12                 2012
#define IDC_EDIT_PARA13                 2013
#define IDC_EDIT_PARA14                 2014
#define IDC_EDIT_PARA15                 2015
#define IDC_EDIT_PARA16                 2016
#define IDC_EDIT_PARA17                 2017
#define IDC_EDIT_PARA18                 2018
#define IDC_EDIT_PARA19                 2019
#define IDC_EDIT_PARA20                 2020
#define IDC_EDIT_PARA21                 2021
#define IDC_EDIT_PARA22                 2022
#define IDC_EDIT_PARA23                 2023
#define IDC_EDIT_PARA24                 2024
#define IDC_EDIT_PARA25                 2025
#define IDC_EDIT_PARA26                 2026
#define IDC_EDIT_PARA27                 2027
#define IDC_EDIT_PARA28                 2028
#define IDC_EDIT_PARA29                 2029
#define IDC_EDIT_PARA30                 2030
#define IDC_EDIT_PARA31                 2031
#define IDC_EDIT_PARA32                 2032
#define IDC_EDIT_PARA33                 2033
#define IDC_EDIT_PARA34                 2034
#define IDC_EDIT_PARA35                 2035
#define IDC_EDIT_PARA36                 2036
#define IDC_EDIT_PARA37                 2037
#define IDC_EDIT_PARA38                 2038
#define IDC_EDIT_PARA39                 2039
#define IDC_EDIT_PARA40                 2040
#define IDC_EDIT_PARA41                 2041
#define IDC_EDIT_PARA42                 2042
#define IDC_EDIT_PARA43                 2043
#define IDC_EDIT_PARA44                 2044
#define IDC_EDIT_PARA45                 2045
#define IDC_EDIT_PARA46                 2046
#define IDC_EDIT_PARA47                 2047
#define IDC_EDIT_PARA48                 2048
#define IDC_EDIT_PARA49                 2049
#define IDC_EDIT_PARA50                 2050
#define IDC_EDIT_PARA51                 2051
#define IDC_EDIT_PARA52                 2052
#define IDC_EDIT_PARA53                 2053
#define IDC_EDIT_PARA54                 2054
#define IDC_EDIT_PARA55                 2055
#define IDC_EDIT_PARA56                 2056
#define IDC_EDIT_PARA57                 2057
#define IDC_EDIT_PARA58                 2058
#define IDC_EDIT_PARA59                 2059
#define IDC_EDIT_PARA60                 2060
#define IDC_EDIT_PARA61                 2061
#define IDC_EDIT_MAIN_LEVEL             3001
#define IDC_EDIT_MAIN_LEVEL_SPAN_MINUS  3002
#define IDC_EDIT_MAIN_LEVEL_SPAN_PLUS   3003
#define IDC_EDIT_CLOSE_LEVEL            3004
#define IDC_EDIT_CLOSE_LEVEL_SPAN_MINUS 3005
#define IDC_EDIT_CLOSE_LEVEL_SPAN_PLUS  3006
#define IDC_EDIT_HIGH_LEVEL             3007
#define IDC_EDIT_CLOSE_LEVEL_DEVIATION_MINUS 3007
#define IDC_EDIT_HIGH_LEVEL_SPAN_MINUS  3008
#define IDC_EDIT_HIGH_LEVEL_SPAN_PLUS   3009
#define IDC_EDIT_CLOSE_HIGH_LEVEL       3010
#define IDC_EDIT_CLOSE_LEVEL_DEVIATION_PLUS 3010
#define IDC_EDIT_CLOSE_HIGH_LEVEL_SPAN_MINUS 3011
#define IDC_EDIT_CLOSE_HIGH_LEVEL_SPAN_PLUS 3012
#define IDC_EDIT_LOW_LEVEL              3013
#define IDC_EDIT_LOW_LEVEL_SPAN_MINUS   3014
#define IDC_EDIT_LOW_LEVEL_SPAN_PLUS    3015
#define IDC_EDIT_CLOSE_LOW_LEVEL        3016
#define IDC_EDIT_CLOSE_LOW_LEVEL_SPAN_MINUS 3017
#define IDC_EDIT_CLOSE_LOW_LEVEL_SPAN_PLUS 3018
#define IDC_EDIT_CLOSE_LEVEL_SPAN_MINUS2 3019
#define IDC_EDIT_CLOSE_LEVEL_SPAN_PLUS2 3020
#define IDC_EDIT_CLOSE_HIGH_LEVEL_SPAN_MINUS2 3021
#define IDC_EDIT_CLOSE_HIGH_LEVEL_DEVIATION_MINUS 3021
#define IDC_EDIT_CLOSE_HIGH_LEVEL_SPAN_PLUS2 3022
#define IDC_EDIT_CLOSE_HIGH_LEVEL_DEVIATION_PLUS 3022
#define IDC_EDIT_CLOSE_LOW_LEVEL_SPAN_MINUS2 3023
#define IDC_EDIT_CLOSE_LOW_LEVEL_SPAN_PLUS2 3024
#define IDC_BUTTON_UPDATE_FIRMWARE      3025
#define IDC_BUTTON_UPDATE_FIRMWARE2     3026
#define IDC_BUTTON_UPDATE_FIRMWARE3     3027
#define IDC_BUTTON_UPDATE_FIRMWARE4     3028
#define IDC_BUTTON_UPDATE_FIRMWARE5     3029

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1211
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
